export const CHANGE_USERNAME_DATE = 'CHANGE_USERNAME_DATE'
export const CHANGE_PASSWORD_DATA = 'CHANGE_PASSWORD_DATA'

export const AUTH = 'AUTH'
export const CLEAR_STATUS = 'CLEAR_STATUS'
export const SIGN_OUT = 'SIGN_OUT'
