export const FETCH_FORM_DATA = 'FETCH_FORM_DATA'

export const CHANGE_USERNAME_DATE = 'CHANGE_USERNAME_DATE'
export const CHANGE_EMAIL_DATE = 'CHANGE_EMAIL_DATE'
export const CHANGE_TASK_DATE = 'CHANGE_TASK_DATE'

export const EDIT_TASK = 'EDIT_TASK'
export const CLEAR_STATUS = 'CLEAR_STATUS'
